//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Cinema.Persistence;

//#nullable disable

//namespace Cinema.Persistence.Migrations
//{
//    [DbContext(typeof(CinemaContext))]
//    [Migration("20241206103308_AddTeacherEntity")]
//    partial class AddTeacherEntity
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.11")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("CourseStudent", b =>
//                {
//                    b.Property<int>("CoursesId")
//                        .HasColumnType("int");

//                    b.Property<int>("StudentsId")
//                        .HasColumnType("int");

//                    b.HasKey("CoursesId", "StudentsId");

//                    b.HasIndex("StudentsId");

//                    b.ToTable("CourseStudent");
//                });

//            modelBuilder.Entity("CourseTeacher", b =>
//                {
//                    b.Property<int>("CoursesId")
//                        .HasColumnType("int");

//                    b.Property<int>("TeachersId")
//                        .HasColumnType("int");

//                    b.HasKey("CoursesId", "TeachersId");

//                    b.HasIndex("TeachersId");

//                    b.ToTable("CourseTeacher");
//                });

//            modelBuilder.Entity("Cinema.Models.Course", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("EndDate")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("NumberOfHours")
//                        .HasColumnType("int");

//                    b.Property<DateTime>("StartDate")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Topic")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.ToTable("Courses");
//                });

//            modelBuilder.Entity("Cinema.Models.Student", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime?>("Birthday")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<string>("PassportNumber")
//                        .IsRequired()
//                        .HasMaxLength(15)
//                        .HasColumnType("nvarchar(15)");

//                    b.Property<string>("Phone")
//                        .HasMaxLength(15)
//                        .HasColumnType("nvarchar(15)");

//                    b.HasKey("Id");

//                    b.ToTable("Students");
//                });

//            modelBuilder.Entity("Cinema.Models.Teacher", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<DateTime?>("Birthday")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.Property<string>("PassportNumber")
//                        .IsRequired()
//                        .HasMaxLength(15)
//                        .HasColumnType("nvarchar(15)");

//                    b.Property<string>("Phone")
//                        .HasMaxLength(15)
//                        .HasColumnType("nvarchar(15)");

//                    b.HasKey("Id");

//                    b.ToTable("Teachers");
//                });

//            modelBuilder.Entity("CourseStudent", b =>
//                {
//                    b.HasOne("Cinema.Models.Course", null)
//                        .WithMany()
//                        .HasForeignKey("CoursesId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Cinema.Models.Student", null)
//                        .WithMany()
//                        .HasForeignKey("StudentsId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("CourseTeacher", b =>
//                {
//                    b.HasOne("Cinema.Models.Course", null)
//                        .WithMany()
//                        .HasForeignKey("CoursesId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Cinema.Models.Teacher", null)
//                        .WithMany()
//                        .HasForeignKey("TeachersId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
