//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Cinema.Persistence;

//#nullable disable

//namespace Cinema.Persistence.Migrations
//{
//    [DbContext(typeof(CinemaContext))]
//    [Migration("20241205141530_RenameCoursesTable")]
//    partial class RenameMovieTable
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.11")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("MovieActor", b =>
//            {
//                b.Property<int>("MoviesId")
//                    .HasColumnType("int");

//                b.Property<int>("ActorsId")
//                    .HasColumnType("int");

//                b.HasKey("MoviesId", "ActorsId");

//                b.HasIndex("ActorsId");

//                b.ToTable("MovieActor");
//            });

//            modelBuilder.Entity("Cinema.Models.Movie", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<string>("Genre")
//                    .HasColumnType("nvarchar(100)");

//                b.Property<int>("DurationMinutes")
//                    .HasColumnType("int");

//                b.Property<string>("Title")
//                    .IsRequired()
//                    .HasMaxLength(100)
//                    .HasColumnType("nvarchar(100)");

//                b.HasKey("Id");

//                b.ToTable("Movies");
//            });

//            modelBuilder.Entity("Cinema.Models.Actor", b =>
//            {
//                b.Property<int>("Id")
//                    .ValueGeneratedOnAdd()
//                    .HasColumnType("int");

//                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                b.Property<DateTime>("BirthDate")
//                    .HasColumnType("datetime2");

//                b.Property<string>("FirstName")
//                    .IsRequired()
//                    .HasMaxLength(50)
//                    .HasColumnType("nvarchar(50)");

//                b.Property<string>("LastName")
//                    .IsRequired()
//                    .HasMaxLength(100)
//                    .HasColumnType("nvarchar(100)");

//                b.HasKey("Id");

//                b.ToTable("Actors");
//            });

//            modelBuilder.Entity("MovieActor", b =>
//            {
//                b.HasOne("Cinema.Models.Movie", null)
//                    .WithMany()
//                    .HasForeignKey("MoviesId")
//                    .OnDelete(DeleteBehavior.Cascade)
//                    .IsRequired();

//                b.HasOne("Cinema.Models.Actor", null)
//                    .WithMany()
//                    .HasForeignKey("ActorsId")
//                    .OnDelete(DeleteBehavior.Cascade)
//                    .IsRequired();
//            });
//#pragma warning restore 612, 618
//        }
//    }
//}
